on: [pull_request]

jobs:
  assign_member_of_team_for_code_review:
    runs-on: ubuntu-latest
    name: A job to assign member of a team, rather than a team
    steps:
    - uses: ./ # Uses an action in the root directory
