on:
  pull_request:
    types: [review_requested]

jobs:
  code_review:
    runs-on: ubuntu-latest
    name: Assign code reviewers
    steps:
    - uses: actions/checkout@v1
    - uses: ./ # Uses an action in the root directory
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
